# Generated by Django 2.2.13 on 2020-06-09 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição')),
                ('brand', models.CharField(max_length=24, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='BuyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('amount', models.FloatField(verbose_name='Quantidade')),
                ('unit', models.CharField(max_length=10, verbose_name='Unidade')),
                ('notes', models.TextField(verbose_name='Observações')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buylist.Product', verbose_name='Produto')),
            ],
        ),
    ]
