# Generated by Django 2.2.13 on 2020-06-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Marca'),
        ),
    ]
