# Generated by Django 2.2.13 on 2020-06-13 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0002_auto_20200611_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buylist',
            name='amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='buylist',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='buylist',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buylist.Product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='buylist',
            name='unit',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidade'),
        ),
    ]
