# Generated by Django 2.2.13 on 2020-06-13 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0003_auto_20200613_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buylist',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='buylist',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='buylist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='buylist',
            name='unit',
        ),
        migrations.CreateModel(
            name='BuyListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Quantidade')),
                ('unit', models.CharField(max_length=10, verbose_name='Unidade')),
                ('notes', models.TextField(verbose_name='Observações')),
                ('buylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buylist.BuyList')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buylist.Product', verbose_name='Produto')),
            ],
        ),
    ]
