# Generated by Django 2.2.13 on 2020-06-16 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0004_auto_20200613_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buylistitem',
            name='buylist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buylist.BuyList', verbose_name='Lista de Compras'),
        ),
    ]
