# Generated by Django 2.2.13 on 2020-06-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0005_auto_20200616_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buylistitem',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
