# Generated by Django 2.2.13 on 2020-06-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buylist', '0007_auto_20200620_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='Seção'),
        ),
    ]
