# Generated by Django 2.2.13 on 2020-07-03 00:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('buylist', '0009_auto_20200621_0505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['description']},
        ),
    ]
